# @name requests.env
@baseUrl = http://localhost:5000
@jwt_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get all todos
GET {{baseUrl}}/api/todo
Accept: application/json
Authorization: Bearer {{jwt_token}}

###

### Create a new todo
POST {{baseUrl}}/api/todo
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "New Todo"
}

###

### Update an existing todo
PUT {{baseUrl}}/api/todo/2
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "id": 2,
  "title": "Updated Todo",
  "isCompleted": true
}

###

### Delete a todo
DELETE {{baseUrl}}/api/todo/2
Authorization: Bearer {{jwt_token}}

###

### Authenticate and get JWT token
POST {{baseUrl}}/api/authenticate
Content-Type: application/json

{
  "username": "your_username",
  "password": "your_password"
}